/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './message.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './message.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_style';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/core/src/linker/template_ref';
var renderType_MessageComponet_Host:import0.RenderComponentType = (null as any);
class _View_MessageComponet_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MessageComponet_0_4:import3.MessageComponet;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageComponet_Host0,renderType_MessageComponet_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-message',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MessageComponet0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MessageComponet_0_4 = new import3.MessageComponet(this.parentInjector.get(import8.MessageService));
    this._appEl_0.initComponent(this._MessageComponet_0_4,[],compView_0);
    compView_0.create(this._MessageComponet_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MessageComponet) && (0 === requestNodeIndex))) { return this._MessageComponet_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MessageComponet_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MessageComponet_Host === (null as any))) { (renderType_MessageComponet_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MessageComponet_Host0(viewUtils,parentInjector,declarationEl);
}
export const MessageComponetNgFactory:import10.ComponentFactory<import3.MessageComponet> = new import10.ComponentFactory<import3.MessageComponet>('app-message',viewFactory_MessageComponet_Host0,import3.MessageComponet);
const styles_MessageComponet:any[] = ['.author[_ngcontent-%COMP%] {\n        display:inline-block;\n        font-style:italic;\n        font-size:12px;\n        width:80%\n    }\n    .config[_ngcontent-%COMP%] {\n        display:inline-block;\n        text-align:right;\n        font-size:12px;\n        width:19%\n    }'];
var renderType_MessageComponet:import0.RenderComponentType = (null as any);
class _View_MessageComponet0 extends import1.AppView<import3.MessageComponet> {
  _text_0:any;
  _el_1:any;
  _NgStyle_1_3:import11.NgStyle;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import12.NgIf;
  _text_12:any;
  _text_13:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageComponet0,renderType_MessageComponet,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,' ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'article',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','panel panel-default');
    this._NgStyle_1_3 = new import11.NgStyle(this.parentInjector.get(import13.KeyValueDiffers),new import14.ElementRef(this._el_1),this.renderer);
    this._text_2 = this.renderer.createText(this._el_1,'\n              ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','panel-body');
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n              ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_1,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','panel-footer');
    this._text_7 = this.renderer.createText(this._el_6,'\n                  ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','author');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                  ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_11 = new import2.AppElement(11,6,this,this._anchor_11);
    this._TemplateRef_11_5 = new import15.TemplateRef_(this._appEl_11,viewFactory_MessageComponet1);
    this._NgIf_11_6 = new import12.NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_6,'\n              ',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'mouseenter',this.eventHandler(this._handle_mouseenter_1_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {backgroundColor: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import12.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6; }
    if (((token === import11.NgStyle) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgStyle_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this._map_0(this.context.color);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgStyle_1_3.ngStyle = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgStyle_1_3.ngDoCheck(); }
    const currVal_4:any = this.context.belongsToUser();
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_11_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'\n                  ',this.context.message.content,'\n              ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_4,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'\n                      ',this.context.message.username,'\n                  ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_9,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_mouseenter_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.color = 'grey')) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MessageComponet0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MessageComponet> {
  if ((renderType_MessageComponet === (null as any))) { (renderType_MessageComponet = viewUtils.createRenderComponentType('D:/read/UDEMY-MEAN/Mongo/angularApp/assets/app/messages/message.component.html',0,import9.ViewEncapsulation.Emulated,styles_MessageComponet,{})); }
  return new _View_MessageComponet0(viewUtils,parentInjector,declarationEl);
}
class _View_MessageComponet1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MessageComponet1,renderType_MessageComponet,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','config');
    this._text_1 = this.renderer.createText(this._el_0,'\n                      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Edit',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                      ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'a',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Delete',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onEdit()) !== false);
    return (true && pd_0);
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onDelete()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MessageComponet1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MessageComponet1(viewUtils,parentInjector,declarationEl);
}